Update README.md
nucleos/NucleosAntiSpamBundle pull request #91
Opened 2020-09-27 12:42 UTC by ThomasLandauer

## Subject

Docs.
Integrating the findings of https://github.com/nucleos/NucleosAntiSpamBundle/pull/86#issuecomment-699484094

2020-09-29 15:11 UTC, core23 requested changes

2020-09-29 15:11 UTC, core23 commented on README.md
> +This bundle provides some basic features to reduce spam in Symfony 4.2+ and PHP 7.3+. It is the successor of `core23/antispam-bundle`, but not related to `isometriks/spam-bundle`.
Please remove the version information, because this will become outdated as soon as the composer requirements will change.

2020-09-29 15:56 UTC, ThomasLandauer commented on README.md
> +This bundle provides some basic features to reduce spam in Symfony 4.2+ and PHP 7.3+. It is the successor of `core23/antispam-bundle`, but not related to `isometriks/spam-bundle`.
I'd like to mention it cause both are pretty strict (e.g. Symfony 3.4 is still supported today). How often do you change this in `composer.json`? Could you maybe set up some script that fetches the numbers from there?

2020-10-03 15:47 UTC, core23 requested changes

2020-10-03 15:47 UTC, core23 commented on README.md
> +This bundle provides some basic features to reduce spam in Symfony 4.2+ and PHP 7.3+. It is the successor of `core23/antispam-bundle`, but not related to `isometriks/spam-bundle`.
I'd like to keep it simple and generic for the docs. If you mention the symfony and php version, you should also mention twig and other dependencies.

2020-10-03 15:47 UTC, core23 commented on README.md
> +{{ email|antispam }}
This example can be confusing. The `antispam` filter can replace long text with multiple e-mails.

2020-10-03 16:16 UTC, ThomasLandauer commented on README.md
> +This bundle provides some basic features to reduce spam in Symfony 4.2+ and PHP 7.3+. It is the successor of `core23/antispam-bundle`, but not related to `isometriks/spam-bundle`.
What I mean: PHP 7.3 is pretty picky. I don't even have it myself on my dev machine ;-) So I'd like to make this more obvious. Don't know how this could be achieved without having to update it manually in the future...

2020-10-03 16:17 UTC, ThomasLandauer commented on README.md
> +{{ email|antispam }}
I "fixed" this by adding a heading to the very top, explaining the bundle in general ;-)

2020-10-03 20:14 UTC, core23 commented on README.md
> +This bundle provides some basic features to reduce spam in Symfony 4.2+ and PHP 7.3+. It is the successor of `core23/antispam-bundle`, but not related to `isometriks/spam-bundle`.
I can understand the fact, that PHP is an environment dependency and can't be changed like any other dependency. But that's a composer problem. If you use PHP 7.1 an older version will be resolved.

For now: I don't want to use any version information in any docs, because they might get changed soon and there's a risk that the docs might not match the current dependencies. You could also require different versions, e.g. symfony config 5 and symfony form 4.

2020-10-03 20:26 UTC, ThomasLandauer commented on README.md
> +This bundle provides some basic features to reduce spam in Symfony 4.2+ and PHP 7.3+. It is the successor of `core23/antispam-bundle`, but not related to `isometriks/spam-bundle`.
OK :-)

2020-10-08 13:36 UTC, core23 approved these changes

2020-10-08 13:36 UTC, merged

2020-10-08 13:37 UTC, core23 commented
Thanks @ThomasLandauer  :+1: